#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

# swp folder
mkdir -pv ~/.tmp
# Link RC files
mkdir -pv bak
for rc in *rc *profile *config tmux.conf; do
  [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
  ln -sfv $BASE/$rc ~/.$rc
done

# Install Homebrew
[ -z "$(which brew)" ] &&
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Packages
brew update
brew install \
  git bash-completion heroku httpie jq macvim python ruby the_silver_searcher \
  tmux vim wget z

# Config
git config --global core.editor $(which vim)
